version: '3.8'
services:
  integrify_db:
    image: postgres:14.1-alpine
    restart: always
    container_name: INTEGRIFY_DB
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  integrify_to_do_app:
      environment:
        - NODE_ENV=development
      build:
        context: ./integrify_code
        dockerfile: Dockerfile
      expose:
        -  "${NODE_JS_EXPOSE_PORT}"
      ports:
        - "${NODE_JS_EXPOSE_PORT}:${NODE_JS_INTERNAL_PORT}"
      command: npm start
      depends_on:
      - integrify_db
volumes:
  db:
    driver: local
